- name: HTTP Server Action
  # You may pin to the exact commit or the version.
  # uses: Eun/http-server-action@856e467dda36cd5d30e93bd7dd168cf3e1676301
  uses: Eun/http-server-action@v1.0.6
  with:
    # Directory to serve
    directory: # optional, default is .
    # Port to serve on
    port: # optional, default is 8080
    # Whether to set the Cache-Control header or not
    no-cache: # optional
    # If set and directory is requested, look for those files, instead of show directory listing
    index-files: # optional, default is []

    # Throw HTTP-Error 405 on other methods than the methods given
    allowed-methods: # optional, default is ["GET", "HEAD"]

    # Content Types to serve
    content-types: # optional, default is {
  "appcache": "text/cache-manifest",
  "css": "text/css",
  "gif": "image/gif",
  "html": "text/html",
  "ico": "image/x-icon",
  "jpeg": "image/jpeg",
  "jpg": "image/jpeg",
  "js": "text/javascript",
  "json": "application/json",
  "png": "image/png",
  "txt": "text/plain",
  "xml": "text/xml"
}
